# Don't fail because of Rails defaults

# Offense count: 5
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'
    - 'app/controllers/test_executions/steps_controller.rb'
    - 'app/helpers/test_executions/steps_helper.rb'
    - 'test/controllers/test_executions/steps_controller_test.rb'
    - 'test/helpers/test_executions/steps_helper_test.rb'

# Offense count: 1
# Configuration parameters: Exclude.
Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/constants.rb'

# Offense count: 3
# Configuration parameters: Exclude.
Style/Documentation:
  Enabled: false
  # Exclude:
  #   - 'app/controllers/application_controller.rb'
  #   - 'app/helpers/application_helper.rb'
  #   - 'config/application.rb'
  #   - 'test/test_helper.rb'

Rails/FindEach:
  Enabled: false

# Offense count: 1
Metrics/ParameterLists:
  Exclude:
    - 'lib/cypress/patient_zipper.rb'
