# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cedar
email: cedar-feedback-list@lists.mitre.org
description: > # this means to ignore newlines until "baseurl:"
  Cedar is a tool for testing the strength of Electronic Clinical Quality Measure (eCQM) collection systems that receive Quality Reporting Document Architecture (QRDA) files.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projectcedar.org" # the base hostname & protocol for your site
github_username:  mitre/cedar

# Build settings
markdown: kramdown
