# Mongoid Configuration for Travis CI
# ===================================
#
development:
  clients:
    default:
      database: cedar_development
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>

measure_eval:
  clients:
    default:
      database: cedar_eval
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>
test:
  clients:
    default:
      database: cedar_test
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>
production:
  clients:
    default:
      database: cedar_production
      hosts:
        - <%= ENV.fetch('MONGO_PORT_27017_TCP_ADDR', 'localhost') %>:<%= ENV.fetch('MONGO_PORT_27017_TCP_PORT', '27017') %>

  options:
    raise_not_found_error: false
