# QRDA documents generated by Cedar are stored here
class Document
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  field :name,                 type: String, default: Faker::Company.name
  field :expected_result,      type: Symbol, default: :reject  # accept, reject
  field :actual_result,        type: Symbol, default: nil      # accept, reject
  field :state,                type: Symbol, default: :failed  # passed, failed
  field :qrda,                 type: String, default: ''
  field :measure_id,           type: String, default: nil

  belongs_to                   :validation
  belongs_to                   :test_execution,
                               inverse_of: :documents
  validates :test_execution,   presence: true
end
